<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <title>@yield('title', 'Pletfix Application')</title>

    <!-- Meta Tags -->

    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="@yield('description', 'Pletfix Homepage')" />
    <meta name="base-url" content="{{ request()->baseUrl() }}"/>

    @yield('metas')

    {{-- importend for SEO - Search Engine Optimizing --}}
    <link rel="canonical" href="@yield('canonical-url', request()->canonicalUrl())"/>

    <!-- Favicon (generated by http://realfavicongenerator.net) -->

    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}"/> {{-- for Phone and iPad --}}
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-32x32.png') }}" /> {{-- for Safari on Mac OS --}}
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-16x16.png') }}" /> {{-- for some other browsers, displayed in the tabs --}}
    {{--<link rel="manifest" href="{{ asset('manifest.json') }}"/> --}}{{-- for Android Chrome - it's a bug, browser will crash after loading page --}}
    <!--suppress HtmlUnknownAttribute -->
    <link rel="mask-icon" href="{{ asset('safari-pinned-tab.svg') }}" color="#5bbad5"/>
    <meta name="theme-color" content="#ffffff"/>

    <!-- Styles -->

    <link rel="stylesheet" href="{{ asset('css/app.css') }}"/>

    @yield('styles')

    <!-- Scripts -->

    <script src="{{ asset('js/app.js') }}"></script>

    <!-- IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <!--suppress HtmlUnknownTarget -->
    <script src="{{ asset('js/ie9/html5shiv.min.js') }}"></script>
    <script src="{{ asset('js/ie9/respond.min.js') }}"></script>
    <![endif]-->

    @yield('scripts')
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">

                <a class="navbar-brand" href="{{ url() }}">Pletfix Application</a>

                <!-- Benutzername -->   
                {{--<span class="collapsed hidden-lg hidden-md hidden-sm">--}}
                    {{--@if (Auth::check())--}}
                        {{--<span class="glyphicon glyphicon-user" aria-hidden="true"></span>--}}
                        {{--{{ Auth::user()->name }}--}}
                    {{--@endif--}}
                {{--</span>--}}

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">

                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li {{ isset($section) && $section == 'home' ? 'class="active"' : ''}}>
                        <a href="{{ url() }}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
{{--                    @if (Auth::guest())--}}
                        <li><a href="{{ url('auth/login') }}"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a></li>
                        <li><a href="{{ url('auth/register') }}"><i class="fa fa-list-alt" aria-hidden="true"></i> Register</a></li>
                    {{--@else--}}
                        {{--<li class="dropdown">--}}
                            {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">--}}
                                {{--<span class="glyphicon glyphicon-user" aria-hidden="true"></span>--}}
                                {{--{{ Auth::user()->name }}--}}
                                {{--<span class="caret"></span>--}}
                            {{--</a>--}}
                            {{--<ul class="dropdown-menu">--}}
                                {{--<li><a href="{{ url('profile') }}">Mein Profil</a></li>--}}
                                {{--<li><a href="{{ url('auth/password/change') }}"><i class="fa fa-key" aria-hidden="true"></i> Kennwort ändern</a></li>--}}
                                {{--<li>--}}
                                    {{--<a href="{{ url('auth/logout') }}" onclick="event.preventDefault(); $(this).next().submit();">--}}
                                        {{--<i class="fa fa-sign-out" aria-hidden="true"></i> Logout--}}
                                    {{--</a>--}}
                                    {{--<form action="{{ url('auth/logout') }}" method="POST" style="display:none">{{ csrf_field() }}</form>--}}
                                {{--</li>--}}
                            {{--</ul>--}}
                        {{--</li>--}}
                        {{--@can('manage-db')--}}
                            {{--<li class="dropdown">--}}
                                {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench" aria-hidden="true"></i> Administration<b class="caret"></b></a>--}}
                                {{--<ul class="dropdown-menu">--}}
                                    {{--<li><a href="{{ url('admin/users') }}">Benutzerverwaltung</a></li>--}}
                                    {{--<!--menuPoint-->--}}
                                    {{--<li class="divider"></li>--}}
                                {{--</ul>--}}
                            {{--</li>--}}
                        {{--@endcan--}}
                    {{--@endif--}}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container content">
        @yield('content')
    </div>
    <footer class="footer">
        <span class="pull-left">
        </span>
        <span class="pull-right">
            Version {{ config('app.version') }}
        </span>
    </footer>
</body>
</html>