<!DOCTYPE html>
<html lang="{{config('app.locale')}}">
<head>
    <title>@yield('title', config('app.name'))</title>

    <!-- Meta Tags -->

    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="@yield('description', 'Pletfix Application')" />
    <meta name="base-url" content="{{request()->baseUrl()}}"/>
    <meta name="csrf-token" content="{{csrf_token()}}"/>

    {{-- importend for SEO - Search Engine Optimizing --}}
    <link rel="canonical" href="@yield('canonical-url', canonical_url())"/>
    @foreach(config('locale.supported') as $locale => $name)
        @if(locale() != $locale)
            <link rel="alternate" hreflang="{{$locale}}" href="{{locale_url($locale)}}"/>
        @endif
    @endforeach

    <!-- Favicon (generated by http://realfavicongenerator.net) -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{asset('apple-touch-icon.png')}}"/> {{-- for Phone and iPad --}}
    <link rel="icon" type="image/png" sizes="32x32" href="{{asset('favicon-32x32.png')}}" /> {{-- for Safari on Mac OS --}}
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('favicon-16x16.png')}}" /> {{-- for some other browsers, displayed in the tabs --}}
    {{--<link rel="manifest" href="{{asset('manifest.json')}}"/> --}}{{-- for Android Chrome - it's a bug, browser will crash after loading page --}}
    <!--suppress HtmlUnknownAttribute -->
    <link rel="mask-icon" href="{{asset('safari-pinned-tab.svg')}}" color="#5bbad5"/>
    <meta name="theme-color" content="#ffffff"/>

    @yield('metas')

    <!-- Styles -->

    <link rel="stylesheet" href="{{asset('css/app.css')}}"/>

    @yield('styles')

    <!-- Scripts -->

    <script src="{{asset('js/app.js')}}"></script>

    <!-- IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <!--suppress HtmlUnknownTarget -->
    <script src="{{asset('js/ie9/html5shiv.min.js')}}"></script>
    <script src="{{asset('js/ie9/respond.min.js')}}"></script>
    <![endif]-->

    @yield('scripts')
</head>
<body>
    <header class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">

                <!-- Branding -->
                <a class="navbar-brand" href="{{url()}}">{{config('app.name')}}</a>

                <!-- Username -->
                <span class="collapsed hidden-lg hidden-md hidden-sm">
                    @if(auth()->isLoggedIn())
                        <span class="glyphicon glyphicon-user" aria-hidden="true" style="top:10px"></span>
                        <span style="position:relative;top:10px">{{auth()->name()}}</span>
                    @endif
                </span>

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">

                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li {{isset($section) && $section == 'home' ? 'class="active"' : ''}}>
                        <a href="{{url()}}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> {{t('app.nav.home')}}</a>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-language" aria-hidden="true"></i> {{t('app.nav.language')}}<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            @foreach(config('locale.supported') as $locale => $name)
                                <li><a href="{{locale_url($locale)}}"><i class="{{locale()==$locale ? 'fa fa-check' :'fa'}}"></i> {{$name}}</a></li>
                            @endforeach
                        </ul>
                    </li>

                    {{--menu_point--}}

                </ul>
            </div>
        </div>
    </header>
    <div class="content">
        @yield('content')
    </div>
    <footer>
        <span class="pull-left">
        </span>
        <span class="pull-right">
            {{t('app.version')}} {{config('app.version')}}
        </span>
    </footer>
</body>
</html>