language: php

php:
  - '5.6'

before_install:
  # set the environment system
  # - sudo apt-get update > /dev/null
  # - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-sqlite
  # - sudo sed -i -e "s,/var/www,$(pwd)/public,g" /etc/apache2/sites-available/default
  # - sudo /etc/init.d/apache2 restart
  - composer self-update

install:
  # create the storage folder
  - mkdir storage && mkdir storage/cache && mkdir storage/db && mkdir storage/logs && mkdir storage/sessions && mkdir storage/temp && mkdir storage/upload
  - chmod 2777 storage/*
  - touch storage/db/sqlite.db

  # create the environment file
  - echo 'APP_ENV=testing' > .env
  - echo 'APP_URL=http://localhost/public' >> .env

  # install dependencies
  - composer install

script:
  # execute the test
  - vendor/bin/phpunit
