language: php

php:
  - '5.6'

before_install:
  # update composer
  - composer self-update

  # start built-in web server
  - php -S localhost:8000 -t public/ router.php > /dev/null 2>&1 &

install:
  # create environment file
  - echo 'APP_ENV=testing' > .env
  - echo 'APP_URL=http://localhost/public' >> .env

  # create storage folder
  - mkdir storage && mkdir storage/cache && mkdir storage/db && mkdir storage/logs && mkdir storage/sessions && mkdir storage/temp && mkdir storage/upload
  - chmod 2777 storage/*
  - touch storage/db/sqlite.db

  # install dependencies
  - composer install

  # copy config
  - cp -n vendor/pletfix/core/config/* config
  - cp -n vendor/pletfix/core/boot/* boot

  # migrate database
  - php console migrate

script:
  # execute the test
  - vendor/bin/phpunit
