#!/usr/bin/env php
<?php

/*
 * Set the base path of the application.
 */
define('BASE_PATH', __DIR__);

/*
 * Register the Composer Autoloader
 *
 * @link https://getcomposer.org/
 */
require __DIR__ . '/vendor/autoload.php';

/*
 * Run...
 */
$status = \Core\Application::console();

exit($status);